title = "VP"
author = "Vincent Parizet"
baseURL = "https://www.vincentparizet.com/blog/"
languageCode = "en-us"
theme = "my-theme"

enableRobotsTXT = true
publishDir = "docs"

[markup]
  [markup.tableOfContents]
    ordered = true
    startLevel = 2
    endLevel = 5
  [markup.highlight]
    style = 'emacs'
    noClasses=false

